sudo: required

jobs:
  include:
  - install: skip
    services:
    - docker
    script:
    - ./make/manylinux1/build_wheels.sh
  - os: osx
    install:
    - ./make/osx/install_python.sh
    script:
    - ./make/osx/build_wheels.sh
